# Generated by Django 3.1.5 on 2021-01-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResizeApp', '0004_auto_20210128_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(blank=True, upload_to='', verbose_name='Файл'),
        ),
    ]
