# Generated by Django 3.1.5 on 2021-01-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResizeApp', '0005_auto_20210128_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(upload_to='', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='image',
            name='link',
            field=models.URLField(blank=True, max_length=255, verbose_name='Ссылка'),
        ),
    ]
