# Generated by Django 3.1.5 on 2021-01-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResizeApp', '0009_auto_20210128_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Файл'),
        ),
    ]
